import twitter
cons_key='HzKE2TVX8hGaCjFcyzYYu4Rp4'
cons_secret='xfsrlU7DBhQqSowL0x69spfbQOHl3q6qgGrsquSqueTN7I5QNF'
acc_token='330185910-8VHJszuC7mop2TyMpN3hZ4kqTRORkHDB9GtuvthV'
acc_secret='ZqlWofGKrpljGK8XIh1zxgwhcykRX22DvdickH2WiLj9E'
api = twitter.Api(consumer_key=cons_key, consumer_secret=cons_secret, access_token_key=acc_token, access_token_secret=acc_secret)
